name: Run Crawler

on:
  workflow_dispatch:
  push:
    branches:
      - v1.5

jobs:
  deploy:
    name: Update Algolia Index
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
        shell: bash

    steps:
         # Checkout the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Docker Container
        run: |
            docker run -e "APPLICATION_ID=AZ2Z9CJSJ0" -e "ALGOLIA_API_KEY=770894548566756df4db4c92bcaf42d9" -e "CONFIG=$(cat config.json | jq -r tostring)" algolia/docsearch-scraper:latest
